### ISSUE TITLE
where did half the API go

### ISSUE THREAD

**Issue by Mercotui** [cesanta/frozen#12]
I cant find `json_parse2`, or `find_json_token` anywhere.
I have tried looking for different branches, but the only thing i found is 
[this documentation](https://docs.cesanta.com/frozen/dev/#/how-to-use/) referencing it.
This used to be part of the mongoose API, but disappeared somewhere in the past 6 months if I'm correct.

What do? halp

**Comment by cpq** [comment]
@Mercotui frozen API has changed .
Either use the old frozen, or upgrade to the new, supposedly superior, API.
