### ISSUE TITLE
json_scanf  example seems incorrect

### ISSUE THREAD

**Issue by ahonkan** [cesanta/frozen#13]
From your online docs:
```
  int a, b;
  char *c;
  json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }",
             &a, &b, &c, scan_array, my_data);

```
It would seem that the actual call should be
```

  int a, b;
  char *c;
  json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }",
             &a, scan_array, my_data, &c, &b );
```
a: %d matches the integer a
b: %M matches the scanner function & user data
c: %Q matches the address of the char* for the string data
d: %B matches bool which gets copied to int b

Am I missing something?

**Comment by cpq** [comment]
@dimonomid  Also check this please.
