### ISSUE TITLE
json_scanf does not interpret null string correctly

### ISSUE THREAD

**Issue by jagoyette** [cesanta/frozen#16]
If a JSON object contains null property values, json_scanf with a %Q formatter converts these properties to a string containing the word "null" instead of a NULL string.

For example, in the sample unit test below, I expect that result should be NULL, but instead it contains the string "null".

  {
    const char *str = "{a : null }";
    char *result = NULL;
    ASSERT(json_scanf(str, strlen(str), "{a: %Q}", &result) == 0);
    ASSERT(result == NULL);
    free(result);
  }

**Comment by cpq** [comment]
@alashkin please verify and integrate

**Comment by alashkin** [comment]
Closed via https://github.com/cesanta/frozen/pull/17
