### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by mutlucg** [cesanta/frozen#23]
Hi,

I'm trying to execute make but it keeps giving me the following error:

![screenshot from 2017-12-10 18-21-12](https://user-images.githubusercontent.com/12023021/33806276-ec652720-ddd6-11e7-9ab3-c39504e1e572.png)

What should I do to fix this? A fast reply would be highly appreciated,

Thank you.

**Comment by cpq** [comment]
Install docker.

**Comment by mutlucg** [comment]
Docker is already installed.

**Comment by BeneVico** [comment]
on ubuntu this worked for me
`sudo apt  install docker.io`
