### ISSUE TITLE
Scan simple array doesn't work - {'b':[1,2]}

### ISSUE THREAD

**Issue by yuvaljacoby** [cesanta/frozen#30]
Hi,

My json looks something like this: "b : [1,2]", I couldn't extract it using json_scanf and callback.

reproduce code (taken from the README.md):

> static void scan_array(const char *str, int len, void *user_data) {
>     struct json_token t;
>     int i;
>     printf("Parsing array: %.*s\n", len, str);
>     for (i = 0; json_scanf_array_elem(str, len, ".x", i, &t) > 0; i++) {
>          printf("We are in the loop");
>     }
> }
> 
> int a, b;
> char *c;
> void *my_data = NULL;
> char *str = "{ a: 123, d: true, b: [1, 2], c: hi }";
> json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }", &a, scan_array, my_data, &c, &b);

It never get's in the loop...
I assume the path shouldn't be ".x" but didn't find any documentation on what it should be (and empty string didn't work)

Thanks!

**Comment by nliviu** [comment]
It works replacing ".x" with empty string ("").
```
static void scan_array(const char *str, int len, void *user_data) {
  struct json_token t;
  int i;
  printf("Parsing array: %.*s\n", len, str);
  for (i = 0; json_scanf_array_elem(str, len, "", i, &t) > 0; i++) {
    printf("Index %d, token [%.*s] (type: %d)\n", i, t.len, t.ptr, t.type);
  }
}
```
Test code:
```
    //Example - scan arbitrary JSON string:
    // str has the following JSON string (notice keys are out of order):
    // { "a": 123, "d": true, "b": [1, 2], "c": "hi" }
    const char* str = "{ a: 123, d: true, b: [1, 2], c: \"hi\" }";
    printf("Example - scan arbitrary JSON string: %s\n", str);

    int a = 0, b = 0;
    char *c = NULL;
    json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }",
               &a, scan_array, NULL, &c, &b);
    printf("a: %d, c: %s, d: %d\n", a, (NULL == c ? "NULL" : c), b);
    if (NULL != c) {
      free(c);
      c = NULL;
    }
    printf("Example - scan arbitrary JSON string end\n");
```
Results:
```
Example - scan arbitrary JSON string: { a: 123, d: true, b: [1, 2], c: "hi" }
Parsing array: [1, 2]
Index 0, token [1] (type: 2)
Index 1, token [2] (type: 2)
a: 123, c: hi, d: 1
Example - scan arbitrary JSON string end
```

**Comment by jkent** [comment]
I created a pulll request #31 to address this documentation bug.  I too was unsure about this at first.
