### ISSUE TITLE
Arduino IDE support

### ISSUE THREAD

**Issue by DanielOgorchock** [cesanta/frozen#33]
I have been using this library in a project of mine (it's great, btw). My project is supporting the Arduino platform. It took some alteration to make the library work correctly on arduino, due to Arduino seemingly lacking support for %.*s syntax in snprintf. I was able to work around this by using temporary buffers in place of the %.*s syntax. 

I'm not sure if this change is desirable for the master version of the library. If Arduino support is desired, I will happily make a pull request.

**Comment by cpq** [comment]
no %.*s, that's predictable that some environments wouldn't have it..
then i'd hesitate to merge.
You might consider https://github.com/cpq/mjson as an alternative.
