### ISSUE TITLE
Example is not perfectly written

### ISSUE THREAD

**Issue by spachner** [cesanta/frozen#35]
Hi,

I tried the first example 'Example - scan arbitrary JSON string:' from README.md and found that:

1) variable 'b' should actually named 'd'.
2) All variables should be initialized before passing their address to json_scanf(). Especially 'b' which is used a boolean. Otherwise the upper 3 bytes are not written by json_scanf() and has random content. I checked all usages of '%B' in the unit test and found that all variables used are initialized. So the example should make that, too.

current:
```
  // str has the following JSON string (notice keys are out of order):
  // { "a": 123, "d": true, "b": [1, 2], "c": "hi" }

  int a, b;
  char *c;
  void *my_data = NULL;
  json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }",
             &a, scan_array, my_data, &c, &b);

```
better:
```
  // str has the following JSON string (notice keys are out of order):
  // { "a": 123, "d": true, "b": [1, 2], "c": "hi" }

  int a = 0, d = 0;
  char *c = NULL;
  void *my_data = NULL;
  json_scanf(str, strlen(str), "{ a:%d, b:%M, c:%Q, d:%B }",
             &a, scan_array, my_data, &c, &d);

```
regards

Stefan

**Comment by vsoral** [comment]
What is the purpose of 'my_data' that is passed to json_scanf?
Is scan_array function meant to populate the values and assign to this?
