### ISSUE TITLE
Supporting arrarys and _ character

### ISSUE THREAD

**Issue by waleedmahmood** [cesanta/frozen#4]
Hi, hope you would be doing great.

Consider following code from main.c from you code files, I've just replaced the static string json with mine. Issue is if string is starting with [ (square brace), function execution ends at parse_json line. I wanted to asked does you code supports json starting with square brackets, i.e., arrays. Also, does its support underscore (_) in keys, e.g., when i replace 'id' with '_id' it give me same behavior as described above.

static const char *test_nested(void) {
    struct json_token ar[100];
    const char *s = "[{\"id\":123,\"bookmark\":1,\"date\":430654481,\"title\":\"Welcome to IE7\",\"url\":\"http://go.microsoft.com/fwlink/?linkid=68919\",\"visits\":1}]";
    enum json_type types[] = {JSON_TYPE_OBJECT, JSON_TYPE_STRING, JSON_TYPE_ARRAY, JSON_TYPE_OBJECT, JSON_TYPE_STRING, JSON_TYPE_NUMBER, JSON_TYPE_STRING, JSON_TYPE_NUMBER, JSON_TYPE_STRING, JSON_TYPE_NUMBER, JSON_TYPE_STRING, JSON_TYPE_STRING, JSON_TYPE_STRING, JSON_TYPE_STRING, JSON_TYPE_STRING, JSON_TYPE_NUMBER, JSON_TYPE_EOF
    };
    int i, ar_size = ARRAY_SIZE(ar), types_size = ARRAY_SIZE(types);
    
    ASSERT(parse_json(s, strlen(s), ar, ar_size) == (int) strlen(s));
    for (i = 0; i < types_size; i++) {
        ASSERT(ar[i].type == types[i]);
    }
    ASSERT(find_json_token(ar, "a[0]") == &ar[3]);
    ASSERT(find_json_token(ar, "a[0][0]") == &ar[4]);
    ASSERT(find_json_token(ar, "a[0][1]") == &ar[5]);
    ASSERT(find_json_token(ar, "a[0][2]") == &ar[6]);
    ASSERT(find_json_token(ar, "a[0][2].b") == &ar[8]);
    
    return NULL;
}

Any help will be appreciated. Thanks in advance.

Cheers. :)

**Comment by tymonx** [comment]
Nope. From [RFC7159](http://www.rfc-editor.org/rfc/rfc7159.txt), **2.  JSON Grammar**. JSON-text = ws value ws

These are the six structural characters:

      begin-array     = ws %x5B ws  ; [ left square bracket
      begin-object    = ws %x7B ws  ; { left curly bracket
      end-array       = ws %x5D ws  ; ] right square bracket
      end-object      = ws %x7D ws  ; } right curly bracket
      name-separator  = ws %x3A ws  ; : colon
      value-separator = ws %x2C ws  ; , comma

Valid JSON text is actually a array or object:

      [ ]
      { }

**Comment by cpq** [comment]
Assigning to @mmikulicic .
Please amend parser & generator functions to conform to JSON spec and allow non-object values (e.g. arrays) to be root level JSON values.

**Comment by w-vi** [comment]
Looks like you are going to fix what is partly in the pull request, great!

**Comment by waleedmahmood** [comment]
I could find time to re-check the updates. If you have fixed, thanks for understanding and updating. I've switch to another third party now.
