### ISSUE TITLE
Invalid licence header in unit_test.c

### ISSUE THREAD

**Issue by arnehaber** [cesanta/frozen#61]
The unit_test.c in the master branch still has the GPL license header: 
https://github.com/cesanta/frozen/blob/master/unit_test.c

`...This library is dual-licensed: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation. For the terms of this
 * license, see <http: *www.gnu.org/licenses/>....`

It should be replaced with a reference to the Apache Commons Licence.

**Comment by cpq** [comment]
Changed to Apache.
